name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Build image and push to container registry'
        required: true
        default: 'true'
        type: boolean
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Your Code
        uses: actions/checkout@v2

      - name: Get runner ID
        if: (github.event.name == 'push' && github.base_ref == 'main') || github.event.inputs.push_image == 'true'
        id: runner_id
        run: |
          RUNNER_ID=$(echo "${{ runner.name }}" | sed 's/[^0-9]*//g')
          echo "Runner ID: ${RUNNER_ID}"
          echo "::set-output name=RUNNER_ID::${RUNNER_ID}"
          
      - name: Say Hello to the World
        # if: (github.event_name == 'pull_request' && github.base_ref == 'main') || github.event.inputs.push_image == 'true'
        # if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main') || github.event.inputs.push_image == 'true'
        if: (github.event.name == 'push' && github.base_ref == 'main') || github.event.inputs.push_image == 'true'
        run: |
          echo "Hello, World!!"
